### ISSUE TITLE
Error on Callback

### ISSUE THREAD

**Issue by baronUKF** [johnRivs/passport-streamlabs#1]
Currently getting this error and I have no idea why. 

TokenError: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the "code" parameter.

**Comment by johnRivs** [comment]
Can you show me the code you're using?

**Comment by baronUKF** [comment]
I used exactly your example code from github.

**Comment by johnRivs** [comment]
You're gonna have to be a bit more specific. Maybe show me the console output because I just tried [the example](https://github.com/johnRivs/passport-streamlabs/blob/master/example/index.js) again and it works fine.

**Comment by baronUKF** [comment]
I copied the example.js. Replaced cookiekey, clientID, clientSecret, scope and callbackURL. On the callbackURL i took the /auth/streamlabs/callback. After approving the app onthe streamlabs site i get following error.

TokenError: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the "code" parameter.
    at Strategy.OAuth2Strategy.parseErrorResponse (D:\...\node_modules\passport oauth2\lib\strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (D:\...\node_modules\passport-oauth2\lib\strategy.js:376:16)
    at D:\...\node_modules\passport-oauth2\lib\strategy.js:166:45
    at D:\....\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (D:\...\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\...\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by johnRivs** [comment]
Please show me the actual code you used after replacing those things. I know it's the same example, but please do.

Also, show me how the URL looks like in the address bar after approving on Streamlabs. Make sure the callback URL you use in your code is the same as the one you have on the Streamlabs app.

**Comment by baronUKF** [comment]
```js
var StreamlabsStrategy = require('passport-streamlabs').Strategy,
    bodyParser         = require('body-parser'),
    cookieParser       = require('cookie-parser'),
    cookieSession      = require('cookie-session'),
    passport           = require('passport'),
    express            = require('express'),
    app                = express();

// Middlewares
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(cookieSession({ secret: '123456789asdfghjhkl' }));
app.use(passport.initialize());
app.use(passport.session());

passport.use(new StreamlabsStrategy({
    clientID:     '',
    clientSecret: '',
    scope:        'donations.read',
    callbackURL:  'http://localhost:3000/auth/streamlabs/callback'
}, function(accessToken, refreshToken, profile, done) {
    return done(undefined, profile);
}));

// User serialization
passport.serializeUser(function(user, done)   { done(null, user); });
passport.deserializeUser(function(user, done) { done(null, user); });

// Routes
app.get('/auth/streamlabs/authorize', passport.authenticate('streamlabs'));

app.get('/auth/streamlabs/callback', passport.authenticate('streamlabs', { failureRedirect: '/auth/streamlabs/authorize' }), function(req, res) {
    // At this point, the authentication was successful.
});

app.get('/protected-route', function(req, res, next) {
    if (req.isAuthenticated()) return next();

    // Not authenticated.
    res.redirect('/auth/streamlabs/authorize');
}, function (req, res) {
    // Good to go.
});

app.get('/logout', function(req, res) {
    req.logout();

    res.redirect('/');
});

app.listen(3000);

```
Checked the streamlabs callback url. They are the same.

URL when error shows up : http://localhost:3000/auth/streamlabs/callback?code=NaF6nGfHp9bODhoBD5IyFCq5UmLlHDMaypaDGkPC

**Comment by johnRivs** [comment]
It works just fine for me. Again, make sure the Redirect URI in the Streamlabs app is the same as `callbackURL`.

Show me how the URL looks like in the address bar after approving on Streamlabs

**Comment by baronUKF** [comment]
![unbenannt-1](https://user-images.githubusercontent.com/26351914/27772571-92ac96e0-5f65-11e7-90c6-30f194cfcdb8.jpg)

Here the screenshot from streamlabs. The file above currently have the right keys in it. Copy and paste it and try it with my keys.

**Comment by johnRivs** [comment]
Tried. Still no error.

See if you can see any of these strings in the browser at any point. Replace these 2 things in the example:
```js
app.get('/auth/streamlabs/callback', passport.authenticate('streamlabs', { failureRedirect: '/auth/streamlabs/authorize' }), function(req, res) {
    // At this point, the authentication was successful.

    res.end('authentication was successful');
});

app.get('/protected-route', function(req, res, next) {
    if (req.isAuthenticated()) return next();

    // Not authenticated.
    res.redirect('/auth/streamlabs/authorize');
}, function (req, res) {
    // Good to go.

    res.end('good to go');
});
```
The first one should appear right after clicking on Approve and the second one should appear after going to /protected-route. If it doesn't work, try reinstalling the package. Or even better, remove the entire node_modules folder and install again.

What version of Node are you using?

**Comment by baronUKF** [comment]
Ok. I think to put res.end was the key 🥇 i dont know why. but now it works. Thanks you for the help :)

**Comment by johnRivs** [comment]
Well, I'm glad it worked, but try without it again because you shouldn't leave those there. Ideally you would want to return a redirect or show some HTML.

If nothing happens and you see no error after removing res.end, then it works.
