### ISSUE TITLE
Access undefined id property on profile without twitch id

### ISSUE THREAD

**Issue by peter-pakanun** [johnRivs/passport-streamlabs#2]
>Strategy.js:31
> id: json.twitch.id,
> TypeError: Cannot read property 'id' of undefined

**Comment by johnRivs** [comment]
I'm gonna need a bit more context on this one. Just tried the [example](https://github.com/johnRivs/passport-streamlabs/tree/master/example) on Node 8.1.4 (npm 5.0.1) and it works fine.
